
export interface ServiceType {
  id: string;
  name: string;
  icon: string; // Name of the Lucide icon
  color: string; // Tailwind color class prefix (e.g., 'blue')
}

export interface ServiceRecord {
  id: string;
  serviceTypeId: string;
  dateTime: string; // ISO string
  location: string;
  notes: string;
  team: string;
  photos: string[]; // Base64 strings
  aiDescription?: string; // Generated by Gemini
  createdAt: number;
}

export interface Team {
  id: string;
  name: string;
}

export enum ViewState {
  DASHBOARD = 'DASHBOARD',
  SERVICE_LIST = 'SERVICE_LIST',
  REPORTS = 'REPORTS',
  TEAMS = 'TEAMS',
  SERVICE_TYPES_MANAGE = 'SERVICE_TYPES_MANAGE'
}

export interface FilterState {
  startDate: string;
  endDate: string;
  serviceTypeId: string; // 'ALL' or specific ID
}
